In [5]:
import pandas as pd


train = pd.read_csv("../dataset/train.csv")
test = pd.read_csv("../dataset/test.csv")
sample_submission = pd.read_csv("../dataset/sample_submission.csv")

In [6]:
# describe Medhod
train[['Promotion1','Promotion2','Promotion3','Promotion4','Promotion5']].describe()

         Promotion1     Promotion2     Promotion3    Promotion4     Promotion5
count   2102.000000    1592.000000    1885.000000   1819.000000    2115.000000
mean    7155.930661    3308.125810    1462.535523   3465.952501    4518.993173
std     8408.206085    9382.823804    9667.580258   6413.116294    6048.661908
min        0.270000    -265.760000     -29.100000      0.410000     135.160000
25%     1844.295000      39.755000       4.700000    499.895000    1742.305000
50%     5221.140000     205.410000      24.600000   1532.630000    3226.410000
75%     9199.242500    1931.005000     104.010000   3640.905000    5444.030000
max    88646.760000  104519.540000  141630.610000  67474.850000  108519.280000