----
# I. Data preprocessing

## 1. Read dataset

In [16]:
import pandas as pd

train = pd.read_csv("dataset/train.csv")
test = pd.read_csv("dataset/test.csv")
submission = pd.read_csv("dataset/sample_submission.csv")

## 2. Missing values handling

### a) `train.csv`

In [17]:
def means(df):
    res = {}
    for i in range(1, 6):
        res[f"Promotion{i}"] = df[f"Promotion{i}"].mean()
    return res


def medians(df):
    res = {}
    for i in range(1, 6):
        res[f"Promotion{i}"] = df[f"Promotion{i}"].median()
    return res


train = train.fillna(0)

### b) `test.csv`

In [18]:
test = test.fillna(value=means(test))

## 3. Data manipulation

### a) `Date`

In [19]:
import datetime as dt


def date_split(date):
    return tuple(map(int, date.split('/')))


def date_to_categorical(df):
    
    pre_store = pre_month = pre_year = -1
    
    for i in range(len(df)):
        store = df.loc[i,'Store']
        month = df.loc[i,'Month']
        year = df.loc[i,'Year']
        if store != pre_store or month != pre_month or year != pre_year:
            cnt = 1
            pre_store = store
            pre_month = month
            pre_year = year
            df.loc[i,'Day'] = cnt
        else:
            cnt += 1
            df.loc[i,'Day'] = cnt
    return df
    

# train
train["Day"] = train["Date"].apply(lambda x: date_split(x)[0])
train["Month"] = train["Date"].apply(lambda x: date_split(x)[1])
train["Year"] = train["Date"].apply(lambda x: date_split(x)[2])
train = date_to_categorical(train)
train = pd.get_dummies(data=train, columns=["Day"])



# test
test["Day"] = test["Date"].apply(lambda x: date_split(x)[0])
test["Month"] = test["Date"].apply(lambda x: date_split(x)[1])
test["Year"] = test["Date"].apply(lambda x: date_split(x)[2])
test = date_to_categorical(test)
test = pd.get_dummies(data=test, columns=["Day"])

### b) `IsHoliday`

In [20]:
# trian
train["IsHoliday"] = train["IsHoliday"].apply(int)

# test
test["IsHoliday"] = test["IsHoliday"].apply(int)

### c) `Store`

In [21]:
# train
train = pd.get_dummies(data=train, columns=["Store"])

# test
test = pd.get_dummies(data=test, columns=["Store"])

### d) `Promotion1`, ... , `Promotion5`

In [22]:
# Scaling
from sklearn.preprocessing import RobustScaler


promos = ['Promotion1','Promotion2','Promotion3','Promotion4','Promotion5']

scaler = RobustScaler()
scaler.fit(train[promos])
train[promos] = scaler.transform(train[promos])
test[promos] = scaler.transform(test[promos])

### e) `Weekly_Sales`

In [23]:
import numpy as np


train["Weekly_Sales"] = np.log1p(train["Weekly_Sales"])

## 4. Remove not using features

In [24]:
removes = ['id','Date','Temperature'] 

train = train.drop(columns=removes)
test = test.drop(columns=removes)
test['Day_5'] = 0

0      0
1      0
2      0
3      1
4      0
      ..
175    1
176    0
177    0
178    0
179    1
Name: Day_4, Length: 180, dtype: uint8

In [25]:
train

,Fuel_Price,Promotion1,Promotion2,Promotion3,Promotion4,Promotion5,Unemployment,IsHoliday,Weekly_Sales,Month,...,Store_36,Store_37,Store_38,Store_39,Store_40,Store_41,Store_42,Store_43,Store_44,Store_45
0,2.572,0.000000,0.0,0.000000,0.000000,0.000000,8.106,0,14.312455,2,...,0,0,0,0,0,0,0,0,0,0
1,2.548,0.000000,0.0,0.000000,0.000000,0.000000,8.106,1,14.311400,2,...,0,0,0,0,0,0,0,0,0,0
2,2.514,0.000000,0.0,0.000000,0.000000,0.000000,8.106,0,14.292967,2,...,0,0,0,0,0,0,0,0,0,0
3,2.561,0.000000,0.0,0.000000,0.000000,0.000000,8.106,0,14.158908,2,...,0,0,0,0,0,0,0,0,0,0
4,2.625,0.000000,0.0,0.000000,0.000000,0.000000,8.106,0,14.256862,3,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6250,3.867,12.335020,60.0,33.248658,36.566951,2.226726,8.684,0,13.506671,8,...,0,0,0,0,0,0,0,0,0,1
6251,3.911,5.752087,128.0,18.830054,9.705248,1.146626,8.684,1,13.549608,9,...,0,0,0,0,0,0,0,0,0,1
6252,3.948,5.952181,0.0,1.538462,17.904453,2.938893,8.684,0,13.462029,9,...,0,0,0,0,0,0,0,0,0,1
6253,4.038,4.409997,922.8,22.626118,12.434619,4.836166,8.684,0,13.491285,9,...,0,0,0,0,0,0,0,0,0,1
6254,3.997,2.377444,206.4,0.536673,8.377427,1.834117,8.684,0,13.477482,9,...,0,0,0,0,0,0,0,0,0,1

In [26]:
test

,Fuel_Price,Promotion1,Promotion2,Promotion3,Promotion4,Promotion5,Unemployment,IsHoliday,Month,Year,...,Store_36,Store_37,Store_38,Store_39,Store_40,Store_41,Store_42,Store_43,Store_44,Store_45
0,3.617,4.214698,646.72,6.518784,18.928523,2.022584,6.573,0,10,2012,...,0,0,0,0,0,0,0,0,0,0
1,3.601,1.088480,646.72,2.901610,3.151902,3.305649,6.573,0,10,2012,...,0,0,0,0,0,0,0,0,0,0
2,3.594,0.495842,646.72,1.763864,0.419915,1.290059,6.573,0,10,2012,...,0,0,0,0,0,0,0,0,0,0
3,3.506,1.349186,317.50,2.146691,5.531683,0.727907,6.573,0,10,2012,...,0,0,0,0,0,0,0,0,0,0
4,3.617,3.150245,646.72,3.592129,15.840982,2.149345,6.170,0,10,2012,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175,3.755,0.020166,26.10,0.350626,6.720423,0.255318,5.217,0,10,2012,...,0,0,0,0,0,0,0,0,1,0
176,3.985,2.633173,646.72,6.733453,11.791272,1.305208,8.667,0,10,2012,...,0,0,0,0,0,0,0,0,0,1
177,4.000,1.020703,646.72,2.822898,3.135995,2.225839,8.667,0,10,2012,...,0,0,0,0,0,0,0,0,0,1
178,3.969,1.045612,646.72,1.137746,2.290461,0.857580,8.667,0,10,2012,...,0,0,0,0,0,0,0,0,0,1
179,3.882,2.096896,580.80,35.778175,1.108995,0.478758,8.667,0,10,2012,...,0,0,0,0,0,0,0,0,0,1

----
# II. Modeling

## 1. Divide `train.csv` into training data and for predicting data

In [27]:
x_train = train.drop(columns=["Weekly_Sales"])
y_train = train["Weekly_Sales"]

## 2. Choose a suitable model

In [28]:
predictions = {}

### a) XGBoost

In [29]:
import time
import xgboost as xgb


start_t = time.time()

model = xgb.XGBRegressor(
    objective='reg:squarederror', 
    learning_rate=0.1, 
    max_depth = 4, 
    n_estimators = 1000
)
model.fit(x_train, y_train)

y_pred = np.expm1(model.predict(test))
predictions["XGBoost"] = y_pred


print(f"[XGBoost] => time: {round(time.time() - start_t, 2)}(sec)")
print(f"{y_pred[0]}, {y_pred[1]}, ... , {y_pred[-1]}")

ValueError: Feature shape mismatch, expected: 60, got 59

----
# III. Submission

In [ ]:
import os


def name(integer):
    return str(integer).zfill(2)


savetime = dt.datetime.now()
folder = "-".join(map(name, [savetime.year, savetime.month, savetime.day]))
sub_folder = name(savetime.hour) + '：' + name(savetime.minute) + '：' + name(savetime.second)

for model in predictions:
    submission["Weekly_Sales"] = predictions[model]
    os.makedirs(f"dataset/submissions/{folder}", exist_ok=True)
    submission.to_csv(f"dataset/submissions/{folder}/{sub_folder+' ('+model+')'}.csv", index=False)
print(f"[Done!] Create {len(predictions)} csv file(s)")